import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";

import SmoothScroll from "../components/smoothScroll";
import PageWrapper from "@/components/loading/PageWrapper";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Luiz Henrique",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body suppressHydrationWarning className={`${figtree.variable} font-fig`}>
        <SmoothScroll />
        <PageWrapper >
          <Header/>
            {children}
          <Footer/>
        </PageWrapper>

      </body>
    </html>
  );
}
