import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";

import SmoothScroll from "../components/smoothScroll";

import HeaderFooterController from "../components/headerFooterController";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Luiz Henrique",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${figtree.variable} font-fig`}>
        <SmoothScroll />
        <HeaderFooterController>
        {children}
        </HeaderFooterController>
      </body>
    </html>
  );
}
